name: deploy CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # - uses: actions/checkout@v2
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}


      # - run: pm2 delete npm --if-present
      - run: git stash
      - run: git pull
      - run: npm ci
      - run: npm run client:i
      - run: npm run client:b:p
      - run: pm2 start npm -- start
